core/
    ai_client.py
    rss_fetcher.py
    publisher.py
    link_manager.py
    image_cache.py
    db.py
    utils.py
templates/
    zh_style_1.txt
    en_style_1.txt
    ms_style_1.txt
    vi_style_1.txt
requirements.txt
README.md（已存在）
